//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assessment_Ahmed_tamer
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_
    {
        public int Userid { get; set; }
        public string username { get; set; }
        public string Password_ { get; set; }
        public Nullable<int> age { get; set; }
        public string gender { get; set; }
        public string Phone { get; set; }
        public string city { get; set; }
    }
}
